/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;

/**
 *
 * @author avlui
 */
public class EntryFrame extends javax.swing.JFrame {

    
    
    private boolean playerOneReady;
    private boolean playerTwoReady;
    private boolean playerThreeReady;
    private boolean playerFourReady;

    public boolean isPlayerOneReady() {
        return playerOneReady;
    }

    public void setPlayerOneReady(boolean playerOneReady) {
        this.playerOneReady = playerOneReady;
    }

    public boolean isPlayerTwoReady() {
        return playerTwoReady;
    }

    public void setPlayerTwoReady(boolean playerTwoReady) {
        this.playerTwoReady = playerTwoReady;
    }

    public boolean isPlayerThreeReady() {
        return playerThreeReady;
    }

    public void setPlayerThreeReady(boolean playerThreeReady) {
        this.playerThreeReady = playerThreeReady;
    }

    public boolean isPlayerFourReady() {
        return playerFourReady;
    }

    public void setPlayerFourReady(boolean playerFourReady) {
        this.playerFourReady = playerFourReady;
    }
    
    
    /**
     * Creates new form EntryFrame
     */
    public EntryFrame() {
        initComponents();
        
        this.setPlayerOneReady(false);
        this.setPlayerTwoReady(false);
        this.setPlayerThreeReady(false);
        this.setPlayerFourReady(false);
        
        this.name1.setVisible(false);
        this.name2.setVisible(false);
        this.name3.setVisible(false);
        this.name4.setVisible(false);
        
        
    }
   
    private void goToBet(){
        System.out.println(this.isPlayerOneReady() + "" + this.isPlayerTwoReady()+""+this.isPlayerThreeReady()+""+this.isPlayerFourReady());
        if(this.isPlayerOneReady()&&this.isPlayerTwoReady()&&this.isPlayerThreeReady()&&this.isPlayerFourReady()) {
            MainFrame goToBet = new MainFrame(this.name1.getText(), this.name2.getText(), this.name3.getText(),this.name1.getText());
            goToBet.setVisible(true);
            this.dispose();           
        }
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backG = new javax.swing.JPanel();
        playerField1 = new javax.swing.JPanel();
        Character1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        nameField1 = new javax.swing.JTextField();
        readyButton1 = new javax.swing.JButton();
        playerField2 = new javax.swing.JPanel();
        Character2 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        nameField2 = new javax.swing.JTextField();
        readyButton2 = new javax.swing.JButton();
        playerField3 = new javax.swing.JPanel();
        Character3 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        nameField3 = new javax.swing.JTextField();
        readyButton3 = new javax.swing.JButton();
        playerField4 = new javax.swing.JPanel();
        Character4 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        nameField4 = new javax.swing.JTextField();
        readyButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 500));
        setResizable(false);

        backG.setBackground(new java.awt.Color(153, 153, 255));
        backG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playerField1.setBackground(new java.awt.Color(255, 255, 255));
        playerField1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 0)));
        playerField1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Character1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/p1.jpg"))); // NOI18N
        playerField1.add(Character1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 170));

        name1.setText("jLabel1");
        name1.setEnabled(false);
        playerField1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        nameField1.setToolTipText("Enter your name");
        playerField1.add(nameField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 130, -1));

        readyButton1.setBackground(new java.awt.Color(255, 255, 255));
        readyButton1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        readyButton1.setText("Ready?");
        readyButton1.setOpaque(false);
        readyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyButton1ActionPerformed(evt);
            }
        });
        playerField1.add(readyButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        backG.add(playerField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 170, 300));

        playerField2.setBackground(new java.awt.Color(255, 255, 255));
        playerField2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 0)));
        playerField2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Character2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/p2.jpg"))); // NOI18N
        Character2.setText("jLabel1");
        playerField2.add(Character2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 170));

        name2.setText("jLabel1");
        name2.setEnabled(false);
        playerField2.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        nameField2.setToolTipText("Enter your name");
        playerField2.add(nameField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 130, -1));

        readyButton2.setBackground(new java.awt.Color(255, 255, 255));
        readyButton2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        readyButton2.setText("Ready?");
        readyButton2.setOpaque(false);
        readyButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyButton2ActionPerformed(evt);
            }
        });
        playerField2.add(readyButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        backG.add(playerField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 170, 300));

        playerField3.setBackground(new java.awt.Color(255, 255, 255));
        playerField3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 0)));
        playerField3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Character3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/p3.jpg"))); // NOI18N
        playerField3.add(Character3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 170));

        name3.setText("jLabel1");
        name3.setEnabled(false);
        playerField3.add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        nameField3.setToolTipText("Enter your name");
        nameField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameField3ActionPerformed(evt);
            }
        });
        playerField3.add(nameField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 150, -1));

        readyButton3.setBackground(new java.awt.Color(255, 255, 255));
        readyButton3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        readyButton3.setText("Ready?");
        readyButton3.setOpaque(false);
        readyButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyButton3ActionPerformed(evt);
            }
        });
        playerField3.add(readyButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        backG.add(playerField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 170, 300));

        playerField4.setBackground(new java.awt.Color(255, 255, 255));
        playerField4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 0)));
        playerField4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Character4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/p4 (1).png"))); // NOI18N
        playerField4.add(Character4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 160, 180));

        name4.setText("jLabel1");
        name4.setEnabled(false);
        playerField4.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        nameField4.setToolTipText("Enter your name");
        playerField4.add(nameField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 213, 150, -1));

        readyButton4.setBackground(new java.awt.Color(255, 255, 255));
        readyButton4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        readyButton4.setText("Ready?");
        readyButton4.setOpaque(false);
        readyButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyButton4ActionPerformed(evt);
            }
        });
        playerField4.add(readyButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        backG.add(playerField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 170, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/mexico-reabren-el-hipodromo-de-las-americas-900x600.jpg"))); // NOI18N
        backG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameField3ActionPerformed

    private void readyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readyButton1ActionPerformed
        String playerNameInput1 = this.nameField1.getText();
        if(!playerNameInput1.equals("")){
            this.name1.setVisible(true);
            this.name1.setText(playerNameInput1);
            this.readyButton1.setBackground(Color.gray);
            this.readyButton1.setText("READY!");
            this.setPlayerOneReady(true);
        }
        this.goToBet();
    }//GEN-LAST:event_readyButton1ActionPerformed

    private void readyButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readyButton2ActionPerformed
        
        String playerNameInput2 = this.nameField2.getText();
        if(!playerNameInput2.equals("")){
            this.name2.setVisible(true);
            this.name2.setText(playerNameInput2);
            this.readyButton2.setBackground(Color.gray);
            this.readyButton2.setText("READY!");
            this.setPlayerTwoReady(true);
        }
        this.goToBet();
    }//GEN-LAST:event_readyButton2ActionPerformed

    private void readyButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readyButton3ActionPerformed
        
        String playerNameInput3 = this.nameField3.getText();
        if(!playerNameInput3.equals("")){
            this.name3.setVisible(true);
            this.name3.setText(playerNameInput3);
            this.readyButton3.setBackground(Color.gray);
            this.readyButton3.setText("READY!");
            this.setPlayerThreeReady(true);
        }
        this.goToBet();
    }//GEN-LAST:event_readyButton3ActionPerformed

    private void readyButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readyButton4ActionPerformed
        
        String playerNameInput4 = this.nameField4.getText();
        if(!playerNameInput4.equals("")){
            this.name4.setVisible(true);
            this.name4.setText(playerNameInput4);
            this.readyButton4.setBackground(Color.gray);
            this.readyButton4.setText("READY!");
            this.setPlayerFourReady(true);
        }
        this.goToBet();
    }//GEN-LAST:event_readyButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Character1;
    private javax.swing.JLabel Character2;
    private javax.swing.JLabel Character3;
    private javax.swing.JLabel Character4;
    private javax.swing.JPanel backG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JTextField nameField1;
    private javax.swing.JTextField nameField2;
    private javax.swing.JTextField nameField3;
    private javax.swing.JTextField nameField4;
    private javax.swing.JPanel playerField1;
    private javax.swing.JPanel playerField2;
    private javax.swing.JPanel playerField3;
    private javax.swing.JPanel playerField4;
    private javax.swing.JButton readyButton1;
    private javax.swing.JButton readyButton2;
    private javax.swing.JButton readyButton3;
    private javax.swing.JButton readyButton4;
    // End of variables declaration//GEN-END:variables
}
